version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postlink-api
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/laravel/.env:/var/www/.env


  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  dbdata:
